config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes do
    collection do
      get :search, to: 'recipes#search'
    end
    resources :comments
  end

  root 'recipes#index'

  resources :categories, except: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  self.per_page = 6
  has_many :recipe_categories
  has_many :recipes, through: :recipe_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  def self.search_by_title(search_term)
    return [] if search_term.blank?

    where('title LIKE ?', "%#{search_term}%").order('created_at DESC')
  end
  acts_as_punchable
  self.per_page = 6
  belongs_to :user
  has_many :comments, dependent: :destroy, inverse_of: :recipe
  has_many :recipe_categories
  has_many :categories, through: :recipe_categories

  has_many :ingredients, dependent: :destroy, inverse_of: :recipe
  accepts_nested_attributes_for :ingredients,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true

  has_many :instructions, dependent: :destroy, inverse_of: :recipe
  accepts_nested_attributes_for :instructions,
                                reject_if: proc { |attributes| attributes['step'].blank? },
                                allow_destroy: true

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 50 }
  validates :user_id, presence: true

  has_attached_file :image, styles: { medium: '400x400#' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :comments

  before_save { self.email = email.downcase }
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: %i[show edit update]
  before_action :require_admin, except: %i[index show]
  def index
    @categories = Category.paginate(page: params[:page]).order('created_At DESC')
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category Successfully Added!!'
      redirect_to categories_path
    else
      render 'new'
      end
  end

  def show
    @category = Category.find(params[:id])
    @category_recipes = @category.recipes
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:success] = 'Category Successfully Updated!!'
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !user_signed_in? || (user_signed_in? && !current_user.admin?)
      flash[:danger] = 'Only admins are allowed to perform this action'
      redirect_to categories_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])

    @comment = @recipe.comments.create(comment_params)
    flash[:success] = 'Commented Successfully !!'
    redirect_to @recipe if @comment.save
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:danger] = 'Comment Deleted !!'
    redirect_to @recipe
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :user_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show search]
  before_action :require_same_user, only: %i[edit update destroy]
  def index
    @recipes = Recipe.paginate(page: params[:page]).sort_by_popularity('DESC').order('created_At DESC')
  end

  def new
    @recipe = current_user.recipes.build
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments
    @recipe.punch(request)
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:success] = 'Recipe Successfully Created!!'
      redirect_to @recipe

    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = 'Recipe Successfully Updated!!'
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    flash[:danger] = 'Recipe Successfully Deleted !!'
    redirect_to root_path, notice: 'Deleted successfully!'
  end

  def search
    @results = Recipe.paginate(page: params[:page]).search_by_title(params[:search_term])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: %i[id name _destroy], instructions_attributes: %i[id step _destroy], category_ids: [])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def require_same_user
    if (current_user != @recipe.user) && !current_user.admin?
      flash[:danger] = 'You can only edit or destroy your own recipe'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/categories/_category.html.haml
%span.badge= link_to category.name, category_path(category)

app/views/categories/_form.html.haml
= render 'shared/errors', obj: @category
= simple_form_for @category, html: { multipart: true} do |f|    
    .panel-body 
        = f.input :name, input_html: { class: 'form-control'}
        %br/                           

    = f.button :submit, class: 'btn btn-lg btn-primary' 

app/views/categories/edit.html.haml
%h1 Edit Category
.row
    .col-md-4.col-md-offset-3
        = render 'form'

    %br/
.col-md-offset-7
    = link_to "Back", categories_path, class: " btn btn-lg btn-default"

        

app/views/categories/index.html.haml
%br/
= link_to "Add Category", new_category_path, class: "btn btn-lg btn-warning"       
.col-md-10.col-sm-offset-2
    %h2 Listing all categories
.col-md-8.col-sm-offset-4    
    = will_paginate @recipies, renderer: BootstrapPagination::Rails
- @categories.each_slice(3) do |category|
    .row
        - category.each do |cat|
            .col-md-4
                .recipe
                    .image_wrapper
                    %h2= link_to cat.name, cat


   

app/views/categories/new.html.haml
%h2 New Category
.row
    .col-md-4.col-md-offset-3
        = render 'form'

    %br/
.col-md-offset-7
    = link_to "Back", categories_path, class: " btn btn-lg btn-default"

        

app/views/categories/show.html.haml
= render "layouts/categories"
.main_content
	#recipe_top.row
		.col-md-11
			#recipe_info
				%h1= @category.name
				- @category_recipes.each_slice(3) do |recipe|
					.row
						- recipe.each do |rec|
							.col-md-4
								.recipe
									.image_wrapper
										= link_to rec do 
											=image_tag rec.image.url(:medium)
									%h2= link_to rec.title, rec 		
	.row
		.col-md-2
			= link_to "Back", root_path, class: "btn btn-info"
		- if user_signed_in? && current_user.admin?			
			= link_to "Edit", edit_category_path, class: "btn btn-primary"

app/views/comments/_comment.html.haml
#panel_comment
  - @comments.each do |com| 
    %h5= com.comment
    %span= com.user.email
    - if current_user == com.user || current_user.admin?
      = link_to "Delete", recipe_comment_path(com.recipe_id, com.id), method: :delete, class: "btn btn-sm btn-danger"

app/views/comments/_form.html.haml
= simple_form_for ([@recipe, @comment]), html: { multipart: true} do |f|    
    .panel-body        
        = f.input :comment, input_html: { class: 'form-control'} 
        = f.hidden_field :user_id, value: current_user.id
        %br/       
        = f.button :submit, class: 'btn- btn-lg btn-warning' 

app/views/layouts/_categories.html.haml
.btn-group
  .col-md-12.col-sm-offset-1
    - Category.all.each do |category|
      %button= link_to "#{category.name}", category_path(category), class:"btn btn-lg"   

app/views/layouts/_footer.html.haml
.container
  %footer.footer
    %small
      Copyright &amp;copy:
      %a{:href => "#"} Subash Khatri
    %nav
      %ul
        %li.nav-item
          = link_to "Recipes", recipes_path, class: 'footer-recipe'

app/views/layouts/_messages.html.haml
.row
  .col-md-10
    - flash.each do |name, msg|
      %div{:class => "alert alert-#{"#{name}"}"}
        %a.close{"data-dismiss" => "alert", :href => "#"} ×
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TestApp
    %link{:href => "https://fonts.googleapis.com/css2?family=Russo+One&display=swap", :rel => "stylesheet"}
    %link{:href => "https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap", :rel => "stylesheet"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"}
    :javascript
      $(document).ready(function(){
        $("#flip_ingredient").click(function(){
          $("#panel_ingredient").slideToggle("fast");
        });
        $("#flip_instruction").click(function(){
          $("#panel_instruction").slideToggle("fast");
        });
        $("#flip_comment").click(function(){
          $("#panel_comment").slideToggle("fast");
        });
      });
    :css
      #panel_ingredient, #panel_instruction, #flip_ingredient, #flip_instruction {
        padding: 5px;
        text-align: center;        
        border: solid 1px #165059;
      }
      
      #panel_ingredient, #panel_instruction, #panel_comment {
        padding: 50px;
      }
      #panel_comment, #flip_comment{
        padding: 10px;
        text-align: center;
        border: solid 1px #fff;   
      }

  %body
  %nav.navbar.navbar-default
    .main_content  
      .navbar-brand= link_to "RMS", root_path
      %ul.nav.navbar-nav.navbar-left
        = form_tag search_recipes_path, class: "span5 for-search", method: "get" do
          %input.search-query(name="search_term" type="text" placeholder="Search for recipe!")
          %button.btn.btn-success(type="submit") Search
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Recipie", new_recipe_path
          %li= link_to "Categories", categories_path if current_user.admin?          
          %li= link_to "My Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          %li= 'Admin' if current_user.admin?
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path 

  
  .container
    = render "layouts/messages"   
      
    = yield
  = render 'layouts/footer'  

app/views/recipes/_form.html.haml
= render 'shared/errors', obj: @recipe
= simple_form_for @recipe, html: { multipart: true} do |f|    
    .panel-body 
        = f.input :title, input_html: { class: 'form-control'}
        = f.input :description, input_html: { class: 'form-control'}
        %br/
        = f.file_field :image, input_html: { class: 'form-control'}

        .row
            .col-md-6
                %h3 Ingredients                
                #ingredients
                    = f.simple_fields_for :ingredients do |ingredient|
                        = render 'ingredient_fields', f: ingredient
                    .links
                        = link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-success add-button"
            .col-md-6
                %h3 Instructions
                #instructions
                    = f.simple_fields_for :instructions do |instruction|
                        = render 'instruction_fields', f: instruction
                    .links 
                        = link_to_add_association 'Add Instruction', f, :instructions, class: "btn btn-success add-button"
        .form-check
            .col-sm-offset-2.col-sm-8
                = f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|
                    - cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text}            
        .col-md-8.col-md-offset-3
            .form-button
                = f.button :submit, class: 'btn btn-md btn-primary' 

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		.field
			= f.input :name, input_html: { class: 'form-input form-control' }
			%br/
			= link_to_remove_association 'Remove', f, class: 'form-button btn btn-danger'

app/views/recipes/_instruction_fields.html.haml
.form-inline.clearfix
    .nested-fields
        .field
            = f.input :step, input_html: { class: 'form-input form-control' }
            %br/
            = link_to_remove_association 'remove step', f, class: 'form-button btn btn-danger'

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

app/views/recipes/index.html.haml
= render "layouts/categories" 
.col-md-10.col-sm-offset-2
    %h1 Recipe Management System
.col-md-6.col-sm-offset-4
    = will_paginate @recipies, renderer: BootstrapPagination::Rails
- @recipes.each_slice(3) do |recipe|
    .row
        - recipe.each do |rec|
            .col-md-4
                .recipe
                    .image_wrapper
                        = link_to rec do 
                            = image_tag rec.image.url(:medium)
                    %h2= link_to rec.title, rec


   

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'
.col-md-6.col-md-offset-2
  = link_to "Back", root_path, class: "btn btn-md btn-warning "

app/views/recipes/search.html.haml
.col-md-6.col-sm-offset-4
    %h3 Search Results!!
.col-md-6.col-sm-offset-4
= will_paginate @results, renderer: BootstrapPagination::Rails
- @results.each_slice(3) do |result|
    .row
        - result.each do |rec|
            .col-md-4
                .recipe
                    .image_wrapper
                        = link_to rec do 
                            = image_tag rec.image.url(:medium)
                    %h2= link_to rec.title, rec


   

app/views/recipes/show.html.haml
= render "layouts/categories"
.main_content
	#recipe_top.row		
		.col-md-4
			= image_tag @recipe.image.url(:medium), class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.title
				%p.description= @recipe.description
				- if @recipe.categories.any?
					%p Categories: 
					= render @recipe.categories
				%p
					Submitted by
					= @recipe.user.email
				%p
					Total Views:
					= @recipe.hits(1.week.ago)				
	.row
		.col-md-6
			#ingredients
				#flip_ingredient
					%h2 Ingredients
				%ul#panel_ingredient
					- @recipe.ingredients.each do |ingredient|
						%li= ingredient.name

		.col-md-6
			#instructions
				#flip_instruction
					%h2 Instructions
				%ul#panel_instruction
					- @recipe.instructions.each do |instruction|
						%li= instruction.step

	.row
	- if user_signed_in?
		.col-md-6
			= render 'comments/form'	
		.col-md-5.col-sm-offset-1
			#flip_comment
				%h4
					%u All comments
			%br/
			= render 'comments/comment'
	%br/		
	.row
		.col-md-12
			= link_to "Back", recipes_path, class: "btn btn-info"
			- if user_signed_in? && (current_user == @recipe.user || current_user.admin?) 
				= link_to "Edit", edit_recipe_path, class: "btn btn-primary"
				= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger"

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .row
    .col-md-8{:style => "margin-left: 15%; "}
      .card
        .card-body{:style => "background-color: rgb(152, 190, 250);"}
          %h2.card-title{:style => "color:red;"}
            = pluralize(obj.errors.count, "error")
            prohibited this from being saved:
          .card-body{:style => "color:red;"}
            %ul
              - obj.errors.full_messages.each do |msg|
                %li
                  = msg
              %ul